initial commit
LamonovaAnna/java-shareit pull request #1
Opened 2022-08-20 17:12 UTC by LamonovaAnna

2022-08-21 19:59 UTC, kukolev requested changes

2022-08-21 19:59 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (text != null && !text.isBlank()) {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

2022-08-21 19:59 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            log.info("Field \"name\" doesn't filled");
При логировании лучше добавлять информацию о текущих значениях параметров, чтобы при анализе было понятно о чем идет речь. Здесь будет полезно добавить значение переменной «item».

2022-08-21 22:29 UTC, LamonovaAnna commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            log.info("Field \"name\" doesn't filled");
Не совсем понятно какое значение добавить, поскольку в данном случае проверяется что поле имя не заполнено.

2022-08-22 12:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            log.info("Field \"name\" doesn't filled");
Да, действительно, согласен. Вопрос снят.

2022-08-22 12:20 UTC, kukolev approved these changes

2022-09-07 18:59 UTC, merged